import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
	{
		_id: uuid(),
		name: "Puma White Sneakers",
		brand: "PUMA",
		type: "Men Sneakers",
		category: "Sneakers",
		imgURL:
			"https://raw.githubusercontent.com/sonishreyas/rippleUI/dev/components/media/images/sneaker.png",
		rating: 4,
		reviews: 400,
		price: 2999,
		mrp: 5999,
		discountPercent: 50,
		discount: 3000,
	},
	{
		_id: uuid(),
		name: "Puma Grey Sneakers",
		brand: "PUMA",
		type: "Men Sneakers",
		category: "Casual Shoes",
		imgURL:
			"https://raw.githubusercontent.com/sonishreyas/ripple-store-app/dev/src/backend/media/images/pume-grey-flourasant.png",
		rating: 4,
		reviews: 31,
		price: 1599,
		mrp: 3999,
		discountPercent: 60,
		discount: 2400,
	},
	{
		_id: uuid(),
		name: "Blue Striped Fire",
		brand: "PUMA",
		type: "Men Sneakers",
		category: "Casual Shoes",
		imgURL:
			"https://raw.githubusercontent.com/sonishreyas/ripple-store-app/dev/src/backend/media/images/puma-blue-striped.png",
		rating: 2,
		reviews: 31,
		price: 2599,
		mrp: 3999,
		discountPercent: 35,
		discount: 1500,
	},
	{
		_id: uuid(),
		name: "Grey Textured Loafers",
		brand: "U.S. Polo Assn.",
		type: "Men Loafers",
		category: "Casual Shoes",
		imgURL:
			"https://raw.githubusercontent.com/sonishreyas/ripple-store-app/dev/src/backend/media/images/us-polo-grey-casual.png",
		rating: 4,
		reviews: 612,
		price: 2159,
		mrp: 3599,
		discountPercent: 40,
		discount: 1440,
	},
	{
		_id: uuid(),
		name: "South Park",
		brand: "Adidas",
		type: "Men Sneakers",
		category: "Sneakers",
		imgURL:
			"https://raw.githubusercontent.com/sonishreyas/ripple-store-app/dev/src/backend/media/images/adidas-casual-green.png",
		rating: 3,
		reviews: 12,
		price: 9899,
		mrp: 10999,
		discountPercent: 10,
		discount: 1100,
	},
	{
		_id: uuid(),
		name: "Printed Slip-On",
		brand: "U.S. Polo Assn.",
		type: "Men Sneakers",
		category: "Casual Shoes",
		imgURL:
			"https://raw.githubusercontent.com/sonishreyas/ripple-store-app/dev/src/backend/media/images/us-polo-casual-sneaker-blue.png",
		rating: 3,
		reviews: 12,
		price: 1799,
		mrp: 2999,
		discountPercent: 40,
		discount: 1200,
	},
	{
		_id: uuid(),
		name: "Leather Slip-Ons",
		brand: "Woodland",
		type: "Slip-On Shoes",
		category: "Formal Shoes",
		imgURL:
			"https://raw.githubusercontent.com/sonishreyas/ripple-store-app/dev/src/backend/media/images/woodland-formal.png",
		rating: 5,
		reviews: 60,
		price: 3195,
		mrp: 5999,
		discountPercent: 45,
		discount: 2804,
	},
	{
		_id: uuid(),
		name: "Velocity Nitro",
		brand: "PUMA",
		type: "Running Shoes",
		category: "Sports Shoes",
		imgURL:
			"https://raw.githubusercontent.com/sonishreyas/ripple-store-app/dev/src/backend/media/images/puma-velocity-sports.png",
		rating: 5,
		reviews: 39,
		price: 8799,
		mrp: 10999,
		discountPercent: 20,
		discount: 2200,
	},
	{
		_id: uuid(),
		name: "Copa Sense.3 TF",
		brand: "Adidas",
		type: "Football Shoes",
		category: "Sports Shoes",
		imgURL:
			"https://raw.githubusercontent.com/sonishreyas/ripple-store-app/dev/src/backend/media/images/adidas-sports.png",
		rating: 4,
		reviews: 45,
		price: 5949,
		mrp: 6999,
		discountPercent: 15,
		discount: 1500,
	},
	{
		_id: uuid(),
		name: "Black Solid Derbys",
		brand: "Bata",
		type: "Formal Shoes",
		category: "Formal Shoes",
		imgURL:
			"https://raw.githubusercontent.com/sonishreyas/ripple-store-app/dev/src/backend/media/images/bata-black-formal.png",
		rating: 4,
		reviews: 120,
		price: 999,
		mrp: 1599,
		discountPercent: 40,
		discount: 600,
	},
	{
		_id: uuid(),
		name: "Black NMD_R1 V2",
		brand: "Adidas",
		type: "Unisex Sneakers",
		category: "Sneakers",
		imgURL:
			"https://raw.githubusercontent.com/sonishreyas/ripple-store-app/dev/src/backend/media/images/adidas-casual-black.png",
		rating: 3,
		reviews: 12,
		price: 10499,
		mrp: 13999,
		discountPercent: 25,
		discount: 3500,
	},
	{
		_id: uuid(),
		name: "Lifestyle Co Sneakers",
		brand: "Roadster",
		type: "Men Casual",
		category: "Casual Shoes",
		imgURL:
			"https://raw.githubusercontent.com/sonishreyas/ripple-store-app/dev/src/backend/media/images/roadster-casual.png",
		rating: 2,
		reviews: 30,
		price: 872,
		mrp: 3795,
		discountPercent: 77,
		discount: 2923,
	},
	{
		_id: uuid(),
		name: "Brown Oxfords",
		brand: "Bata",
		type: "Oxfords",
		category: "Formal Shoes",
		imgURL:
			"https://raw.githubusercontent.com/sonishreyas/ripple-store-app/dev/src/backend/media/images/bata-brown-formal.png",
		rating: 3,
		reviews: 175,
		price: 1799,
		mrp: 2599,
		discountPercent: 30,
		discount: 800,
	},
	{
		_id: uuid(),
		name: "Fisherman Sandals",
		brand: "Bata",
		type: "Sandals",
		category: "Sandles & Floaters",
		imgURL:
			"https://raw.githubusercontent.com/sonishreyas/ripple-store-app/dev/src/backend/media/images/bata-sandles.png",
		rating: 4,
		reviews: 175,
		price: 1529,
		mrp: 1699,
		discountPercent: 10,
		discount: 170,
	},
	{
		_id: uuid(),
		name: "Colourblocked Leather",
		brand: "Woodland",
		type: "Men Casual",
		category: "Casual Shoes",
		imgURL:
			"https://raw.githubusercontent.com/sonishreyas/ripple-store-app/dev/src/backend/media/images/woodland-casual.png",
		rating: 4,
		reviews: 12,
		price: 3310,
		mrp: 3895,
		discountPercent: 15,
		discount: 585,
	},
	{
		_id: uuid(),
		name: "Patterned Socks",
		brand: "U.S. Polo Assn.",
		type: "Socks",
		category: "Socks",
		imgURL:
			"https://raw.githubusercontent.com/sonishreyas/ripple-store-app/dev/src/backend/media/images/socks.png",
		rating: 4,
		reviews: 152,
		price: 499,
		mrp: 999,
		discountPercent: 50,
		discount: 500,
	},
	{
		_id: uuid(),
		name: "Lifestyle Co Sandles",
		brand: "Roadster",
		type: "Sandals",
		category: "Sandles & Floaters",
		imgURL:
			"https://raw.githubusercontent.com/sonishreyas/ripple-store-app/dev/src/backend/media/images/roadster-sandles.png",
		rating: 1,
		reviews: 4,
		price: 797,
		mrp: 2659,
		discountPercent: 70,
		discount: 1862,
	},
];
